### ISSUE TITLE
Compatibility with matplotlib 3.8?

### ISSUE THREAD

**Issue by billbrod** [swfiua/blume#5]
With a fresh install of matplotlib (version 3.8) and blume (version 0.2.5.4) on python 3.10, when I try to import `blume.table` I get the following error:
```python
>>> from blume import table
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/billbrod/miniconda3/envs/test/lib/python3.10/site-packages/blume/table.py", line 23, in <module>
    from matplotlib import artist, cbook, docstring
ImportError: cannot import name 'docstring' from 'matplotlib' (/home/billbrod/miniconda3/envs/test/lib/python3.10/site-packages/matplotlib/__init__.py)
```

it [looks like](https://matplotlib.org/stable/api/docstring_api.html) matplotlib is removing their `docstring` API. Is it possible to remove this behavior?

**Comment by swfiua** [comment]
Thanks for letting me know.

I've put out a fix here with docstring removed:

https://github.com/swfiua/blume/commit/3f7639483b51651fec175b99935bf10c3b4c4f45

Also put out a new 2.5.4 release on pypy.

**Comment by swfiua** [comment]
Put out a new release 0.2.5.5 that should work with 3.8 -- I've removed the use of matplotlib.docstring

**Comment by billbrod** [comment]
Looks like this fixed the issue for me, thanks!

**Comment by swfiua** [comment]
Thanks for testing it out.
